version: '2'
services:
  redis:
    image: redis
    ports:
      - "6379:6379"
  phpfpm:
    build: ./php7-fpm/
    links:
      - redis:redis
    volumes:
      - ./src:/data
#  nginx:
#    build: ./nginx/
#    ports:
#      - "80:80"
#    links:
#      - phpfpm:phpfpm
#    volumes:
#      - ./src:/data